[tool.poetry]
name = "viajero"
version = "0.1.0"
description = ""
authors = ["José Antonio Zumaquero Torres <jazumaquer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
